%macro eligtable_insertmacro();
    insert into bestairreport_out (total, inc01, inc02, inc03, inc04, exc01,
                  exc02, exc03, exc04, exc05, exc06, exc07, exc08, exc09, exc10,
                  exc11, exc12, meets, agree, dnagr, dnres, dnbus, dnwrk, dntra, dndis,
                  dntst, dnpas, dnpap, dnoth, dnphy)
    select  count(elig_studyid) as total,
        count(elig_incl01agerange) as inc01,
        count(elig_incl02infconsent) as inc02,
        count(elig_incl03osa) as inc03,
        count(elig_incl04cvd) as inc04,
        count(elig_excl01ejec) as exc01,
        count(elig_excl02miproc) as exc02,
        count(elig_excl03poorhyper) as exc03,
        count(elig_excl04strokeimp) as exc04,
        count(elig_excl05medprob) as exc05,
        count(elig_excl06oxsat) as exc06,
        count(elig_excl07pap) as exc07,
        count(elig_excl08sixhrsbed) as exc08,
        count(elig_excl09epworth) as exc09,
        count(elig_excl10driver) as exc10,
        count(elig_excl11csa) as exc11,
        count(elig_excl12refusal) as exc12,
        count(elig_meetstatus) as meets,
        count(elig_partstatusagree) as agree,
        count(elig_partstatusdnagr) as dnagr,
        count(elig_notinterested) as dnres,
        count(elig_toobusy) as dnbus,
        count(elig_misswork) as dnwrk,
        count(elig_transportation) as dntra,
        count(elig_distance) as dndis,
        count(elig_extratests) as dntst,
        count(elig_passive) as dnpas,
        count(elig_onlycpap) as dnpap,
        count(elig_otherreason) as dnoth,
        count(elig_physiciandoesnotgrant) as dnphy

%mend;
